export enum AuthTenantErrorCode {
  AUTH_MISSING_TOKEN = 'AUTH_MISSING_TOKEN',
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  AUTH_VERIFICATION_REQUIRED = 'AUTH_VERIFICATION_REQUIRED',
  TENANT_CONTEXT_REQUIRED = 'TENANT_CONTEXT_REQUIRED',
  TENANT_ACCESS_DENIED = 'TENANT_ACCESS_DENIED',
  PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
  PRODUCT_DUPLICATE_BARCODE = 'PRODUCT_DUPLICATE_BARCODE',
  PRODUCT_VERSION_CONFLICT = 'PRODUCT_VERSION_CONFLICT',
  PRODUCT_INVALID_STOCK_ROWS = 'PRODUCT_INVALID_STOCK_ROWS',
  CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND',
  CUSTOMER_DUPLICATE_PHONE = 'CUSTOMER_DUPLICATE_PHONE',
  CUSTOMER_DUPLICATE_EMAIL = 'CUSTOMER_DUPLICATE_EMAIL',
  CUSTOMER_VERSION_CONFLICT = 'CUSTOMER_VERSION_CONFLICT',
  TRANSACTION_NOT_FOUND = 'TRANSACTION_NOT_FOUND',

  // Transaction mutation contract-phase errors (Phase 3B)
  TRANSACTION_MUTATION_INVALID_OPERATION = 'TRANSACTION_MUTATION_INVALID_OPERATION',
  TRANSACTION_MUTATION_INVALID_REQUEST = 'TRANSACTION_MUTATION_INVALID_REQUEST',
  TRANSACTION_MUTATION_INVALID_SETTLEMENT = 'TRANSACTION_MUTATION_INVALID_SETTLEMENT',
  TRANSACTION_MUTATION_INVALID_RETURN_MODE = 'TRANSACTION_MUTATION_INVALID_RETURN_MODE',
  TRANSACTION_MUTATION_IDEMPOTENCY_KEY_REQUIRED = 'TRANSACTION_MUTATION_IDEMPOTENCY_KEY_REQUIRED',
  TRANSACTION_MUTATION_IDEMPOTENCY_KEY_REUSED_DIFFERENT_PAYLOAD = 'TRANSACTION_MUTATION_IDEMPOTENCY_KEY_REUSED_DIFFERENT_PAYLOAD',
  TRANSACTION_MUTATION_IDEMPOTENCY_REPLAY = 'TRANSACTION_MUTATION_IDEMPOTENCY_REPLAY',
  TRANSACTION_MUTATION_PREVIEW_REQUIRED = 'TRANSACTION_MUTATION_PREVIEW_REQUIRED',
  TRANSACTION_MUTATION_PREVIEW_EXPIRED = 'TRANSACTION_MUTATION_PREVIEW_EXPIRED',
  TRANSACTION_MUTATION_VERSION_CONFLICT = 'TRANSACTION_MUTATION_VERSION_CONFLICT',
  TRANSACTION_MUTATION_INSUFFICIENT_STOCK = 'TRANSACTION_MUTATION_INSUFFICIENT_STOCK',
  TRANSACTION_MUTATION_COMPENSATION_REQUIRED = 'TRANSACTION_MUTATION_COMPENSATION_REQUIRED',
  TRANSACTION_MUTATION_COMPENSATION_INVALID = 'TRANSACTION_MUTATION_COMPENSATION_INVALID',
  TRANSACTION_MUTATION_BLOCKED = 'TRANSACTION_MUTATION_BLOCKED',
}

export type StandardErrorEnvelope = {
  code: string;
  message: string;
  fieldErrors: Array<{ field: string; message: string }>;
  requestId: string | null;
  timestamp: string;
};
