import { apiRequest } from '@/services/apiClient';
export type PurchaseParty = { id: string; storeId: string; name: string; phone: string | null; gst: string | null; location: string | null; contactPerson: string | null; notes: string | null; isArchived: boolean; archivedAt: string | null; createdAt: string; updatedAt: string; version: number };
export type PurchaseOrderLine = { productName: string; productId?: string; sourceType: 'inventory' | 'new'; variant?: string; color?: string; quantity: number; unitCost: number; pendingProductBarcode?: string; category?: string; image?: string };
export type PurchaseOrder = { id: string; storeId: string; partyId: string; partyName: string; status: 'draft' | 'placed' | 'received' | 'cancelled'; orderDate: string; billNumber: string | null; billDate: string | null; gstPercent: number; lines: PurchaseOrderLine[]; totalQuantity: number; totalAmount: number; notes: string | null; receivedQuantity: number; createdAt: string; updatedAt: string; version: number };
export type ReceiveOrderRequest = { orderId: string; expectedVersion?: number; receiveMethod: 'avg_method_1' | 'avg_method_2' | 'no_change' | 'latest_purchase'; note?: string };
export const procurementClient = {
  listParties(query?: { q?: string; includeArchived?: boolean }, token?: string | null) { const params = new URLSearchParams(); if (query?.q) params.set('q', query.q); if (query?.includeArchived !== undefined) params.set('includeArchived', String(query.includeArchived)); return apiRequest<{ items: PurchaseParty[] }>({ path: `/procurement/parties${params.toString() ? `?${params.toString()}` : ''}`, token }); },
  getPartyById(id: string, token?: string | null) { return apiRequest<{ party: PurchaseParty }>({ path: `/procurement/parties/${id}`, token }); },
  createParty(payload: Partial<PurchaseParty>, token?: string | null) { return apiRequest<{ party: PurchaseParty }>({ path: '/procurement/parties', method: 'POST', body: payload, token }); },
  updateParty(id: string, payload: Partial<PurchaseParty> & { expectedVersion?: number }, token?: string | null) { return apiRequest<{ party: PurchaseParty }>({ path: `/procurement/parties/${id}`, method: 'PATCH', body: payload, token }); },
  listOrders(query?: { q?: string; status?: string; partyId?: string }, token?: string | null) { const params = new URLSearchParams(); if (query?.q) params.set('q', query.q); if (query?.status) params.set('status', query.status); if (query?.partyId) params.set('partyId', query.partyId); return apiRequest<{ items: PurchaseOrder[] }>({ path: `/procurement/orders${params.toString() ? `?${params.toString()}` : ''}`, token }); },
  getOrderById(id: string, token?: string | null) { return apiRequest<{ order: PurchaseOrder }>({ path: `/procurement/orders/${id}`, token }); },
  createOrder(payload: Partial<PurchaseOrder>, token?: string | null) { return apiRequest<{ order: PurchaseOrder }>({ path: '/procurement/orders', method: 'POST', body: payload, token }); },
  updateOrder(id: string, payload: Partial<PurchaseOrder> & { expectedVersion?: number }, token?: string | null) { return apiRequest<{ order: PurchaseOrder }>({ path: `/procurement/orders/${id}`, method: 'PATCH', body: payload, token }); },
  receiveOrder(id: string, payload: ReceiveOrderRequest, token?: string | null) { return apiRequest<{ status: 'applied' | 'replayed'; mutationId: string; requestId: string; idempotencyKey: string; orderId: string }>({ path: `/procurement/orders/${id}/receive`, method: 'POST', body: payload, token }); },
};
